local function post(color, title, description, embedFields, url)
    local data = {
        embeds = {{
            title = title or "",
            description = description or "",
            fields = embedFields or {},
            timestamp = os.date("!%Y-%m-%dT%H:%M:%SZ"),
            color = colorcodes[color]
        }}
    }
    
    local success, err = pcall(function()
        return HttpService:RequestAsync({
            Url = url,
            Method = "POST",
            Body = HttpService:JSONEncode(data),
            Headers = {
                ["Content-Type"] = "application/json",
                ["apikey"] = "" -- your Ro-Tracker Api Key generated by running /getrotrackerapit
            }
        })
    end)
    
    if not success then
        warn("Failed to send webhook! Error: " .. err.Body)
    end
end

local embedFields = {
    { name = "Field 1", value = "Value 1", inline = true },
    { name = "Field 2", value = "Value 2", inline = false }
}

post("green", "Test Embed", "This is a test embed message", embedFields, " webhook url generated by converting your webhook url on https://sufi.homes/pages/sufiprox.html")
