import requests

url = "" # webhook url generated by converting your webhook url on https://sufi.homes/pages/sufiprox.html

payload = {
    "username": "RandomUser",
    "avatar_url": "https://randomuser.me/api/portraits/men/1.jpg",
    "content": "This is a message with an embed",
    "embeds": [
        {
            "title": "Test Embed",
            "description": "This is a test embed with fields",
            "color": 16711680,  # This is the decimal representation of the color red
            "fields": [
                {
                    "name": "Field 1",
                    "value": "This is the value for field 1",
                    "inline": False
                },
                {
                    "name": "Field 2",
                    "value": "This is the value for field 2",
                    "inline": False
                }
            ]
        }
    ]
}

headers = {
    'Content-Type': 'application/json',
    'User-Agent': 'YourAppName/1.0',
    'apikey': "" # your Ro-Tracker Api Key generated by running /getrotrackerapi
}

response = requests.post(url, json=payload, headers=headers)

print(response.status_code)
print(response.json())
